echo "Usernames & Passwords"
echo "site:$1 intext:\"username\" intext:\"password\" -git"
echo "site:$1 filetype:txt OR filetype:log \"username\" OR \"password\""
echo "site:$1 inurl:admin OR inurl:login OR inurl:portal"
echo "site:pastebin.com \"password\" OR \"login\" OR \"credentials\""
echo ""
echo ""

echo "Hardcoded Credentials in Configuration Files"
echo "site:$1 filetype:env \"DB_PASSWORD=\" OR \"DB_USER=\""
echo "site:$1 filetype:json \"AWS_ACCESS_KEY_ID=\" OR \"AWS_SECRET_ACCESS_KEY=\""
echo "site:$1 filetype:config \"password=\" OR \"apikey=\""
echo ""
echo ""

echo "Exposed SSH Keys & Private Keys"
echo "site:$1 filetype:pem OR filetype:key \"BEGIN RSA PRIVATE KEY\""
echo "site:$1 \"BEGIN OPENSSH PRIVATE KEY\""
echo ""
echo ""

echo "Internal & Confidential Documents"
echo "site:$1 filetype:pdf OR filetype:doc OR filetype:xls \"confidential\" OR \"internal use only\""
echo "site:$1 filetype:xls OR filetype:csv \"employee salary\" OR \"payroll\""
echo "site:$1 filetype:docx \"restricted\" OR \"not for public release\""
echo "site:$1 ext:doc | ext:docx | ext:pdf | ext:xls | ext:xlsx | ext:csv | ext:sql | ext:txt | ext:conf | ext:key | ext:crt | ext:pfx | ext:py | ext:html | ext:sh"
echo "inurl:$1 \"not for distribution\" | confidential | \"employee only\" | proprietary | \"top secret\" | internal | private filetype:xls OR filetype:csv OR filetype:pdf"
echo ""
echo ""

echo "Exposed Source Code Containing Secrets"
echo "site:$1 filetype:php OR filetype:js OR filetype:env \"DB_PASSWORD=\""
echo "site:$1 intitle:\"index of\" \"config.php\""
echo "site:github.com \"password\" OR \"api_key\" OR \"secret_key\""
echo ""
echo ""

echo "Financial & Payment Information"
echo "site:$1 intext:\"credit card number\" OR \"CVV\" OR \"Visa\" OR \"MasterCard\""
echo "site:$1 intext:\"bank account number\" OR \"routing number\""
echo "site:$1 filetype:xls OR filetype:csv \"financial report\""
echo ""
echo ""

echo "Server & Configuration Leaks"
echo "site:$1 filetype:log OR filetype:txt \"error log\" OR \"debug log\""
echo "site:$1 intitle:\"index of\" \"backup\""
echo "site:$1 filetype:sql \"database dump\" OR \"backup\""
echo "site:$1 ext:bkf | ext:bkp | ext:bak | ext:old | ext:backup"
echo "site:$1 intitle:\"index of\" | ext:log | ext:swf | inurl:shell | inurl:backdoor | inurl:wso | inurl:cmd | shadow | passwd | boot.ini"
echo ""
echo ""

echo "Cloud & API Keys Exposure"
echo "site:$1 filetype:json \"google_api_key=\" OR \"firebase_api_key=\""
echo "site:$1 \"api_key\" OR \"access_token\" OR \"client_secret\""
echo ""
echo ""

echo "Configuration Files"
echo "site:$1 ext:xml | ext:conf | ext:ini | ext:cfg | ext:env | ext:rdp | ext:reg"
echo ""
echo ""

echo "Misconfigured & Open Directories"
echo "site:$1 intitle:\"index of\" \"parent directory\""
echo "site:$1 intitle:\"index of\" \"private\" OR \"confidential\""
echo "site:$1 intitle:\"index of\" \"backup\" OR \"database\""
echo ""
echo ""

echo "Exposed Admin Panels & Dashboards"
echo "site:$1 inurl:admin OR inurl:dashboard OR inurl:secure"
echo "site:$1 \"admin panel\" OR \"restricted access\""
echo ""
echo ""

echo "Exposed git Repositories"
echo "inurl:\"/.git\" $1 -github"
echo ""
echo ""

echo "SQL errors"
echo "site:$1 intext:\"sql syntax near\" | intext:\"syntax error has occurred\" | intext:\"unexpected end of SQL command\" | intext:\"Warning: mysql_connect()\""
echo ""
echo ""

echo "Sensitive Emails & Contact Information"
echo "site:$1 intext:\"internal use only\" OR \"do not distribute\""
echo "site:$1 intext:\"classified\" OR \"sensitive information\""
echo "site:$1 \"employee email\" OR \"staff contact\""
echo ""
echo ""
